name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Update remote mods
        run: yarn update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update mods
          delete-branch: true
          title: Scheduled mod update
